### ISSUE TITLE
Error running uninstall.php

### ISSUE THREAD

**Issue by plankobostjan** [PiPass/blockpage#23]
Running _uninstall.php_ throws:
`PHP Parse error:  syntax error, unexpected 'echo' (T_ECHO), expecting ',' or ';' in /home/pi/PiPass/setup/uninstall.php on line 3
`

**Reason for the error:**
There's a semicolon missing in the second line of the _uninstall.php_ script.

**Comment by JoeSchubert** [comment]
This isn't part of a release yet and it's currently just code that was tossed together as an idea for how it would look from a comment in one of my pull requests. There are also other issues in it still, like the hardcoded webroot path.

Thanks for the feedback. It should be fixed in the next release.

Just to make sure though. You didn't get this file during running install per the provided instructions or updating, correct? Also, did it work for you otherwise?

**Comment by plankobostjan** [comment]
Oh, okay. I didn't realize that.

No, I didn't get that file using provided instructions. I just cloned the repo and played around a bit.

Otherwise, the script works, but not perfectly. It doesn't remove the _README.md_ file and .git folder. README.md is not a problem, but leaving .git folder results in 
`fatal: remote origin already exists.`
error if you try to reinstall PiPass using provided instructions.

Hope that helps. :)
