### ISSUE TITLE
suggestion: show reason for blocking

### ISSUE THREAD

**Issue by iroQuai** [PiPass/blockpage#6]
a long time before PiPass there was a project like this, WaLLy3K's Block Page. I believe (big) parts of it where merged in the pi-hole code v3.2

What I really liked about this block page was that it showed the reason why a page was blocked. Is this something that is easily integrated in this project? Would be awesome!

(info about WaLLy3K's block page here: https://github.com/WaLLy3K/Pi-hole-Block-Page)

**Comment by JoeSchubert** [comment]
I think that this is outside the scope of this project. 

The blocking is done from pihole. This is simply a page that gets served to the end users to allow them to still access a blocked page.

Ultimately, the pages that pihole blocks are from your blacklists. If you're just using/trusting blacklists from the internet, that would be something that would need to be brought up to the maintainers of said lists.

I doubt that pihole would support this either since it's not really "blocking" any sites... It just blocks the dns loookup. You would still be able to access it by IP perfectly fine since there is no dns lookup.

**Comment by roenw** [comment]
It would be possible, and I personally think it's a good idea. Though it's currently not a priority.
