### ISSUE TITLE
Just wandering if this will work with the new V5 BETA

### ISSUE THREAD

**Issue by flipptx** [PiPass/blockpage#69]
Just wandering if this will work with the new V5 BETA

**Comment by roenw** [comment]
The only potentially breaking change that I see is the migration to the gravity.db file, but PiPass shouldn't be affected since it doesn't directly manipulate those files - it uses Pi-Hole's CLI to do that.

If you are curious, I would take a backup of your Pi-Hole and try it out. I may spin up a VM sometime soon and try it myself.

**Comment by roenw** [comment]
If you need additional help, please create a thread on the [PiPass forum](https://forum.pipass.net/).
