### ISSUE TITLE
Show PiPAss block / allow pages based on IP Address

### ISSUE THREAD

**Issue by cktechie2012** [PiPass/blockpage#8]
Can we have PiPass enabled for specific IP addresses... Example I use Pihole disable to block tons of ads on Apple TV, Roku, Vizio TV and Fire TV and also on my laptop and Smartphones / Tablets at home and VPN.

Block page should appear only for Laptops, Smartphones and Tablets and not for TV / Apple TV / Roku / FireTV based on IP addresses?

**Comment by iroQuai** [comment]
Is this pipass specific or PiHole in general? Because if it's PiHole in general, please check this out: https://discourse.pi-hole.net/t/unblocking-a-single-devices/656

**Comment by cktechie2012** [comment]
This is PiPass specific. PiHole is setup only as a DNS blocker, with the router setting the DNS for the entire network. PiPass should have possible feature to enable the block / allow feature for specific devices like smart phones and not the TV devices - this may slow down the whole viewing.

**Comment by JoeSchubert** [comment]
I think that this is outside the scope of pipass specifically. Keep in mind that pipass is serving a page for 404's. Assuming that you don't need to ever access anything in the webserver from these ips, you could just block them from your webserver. For instance, lighthttpd:
https://www.cyberciti.biz/tips/lighttpd-restrict-or-deny-access-by-ip-address.html

**Comment by cktechie2012** [comment]
Its more of option to block ads, and if a legit site is encountered on browsing from laptop or smartphone, be able to bypass it.

**Comment by roenw** [comment]
This shouldn't be necessary if I understand what you're saying correctly. Let's say that you were running Hulu on your Apple TV, and Hulu tries to load an ad. It goes to Pi-Hole and requests DNS, Pi-Hole returns it's own IP. Hulu is requesting a video response back, not an HTML page. It receives an HTML file back, and ends up failing instead of displaying the blockpage.

At least, this is how it works at my house. PiPass has not caused any issues yet. Please give more details on why this would be necessary, or correct me if I'm misunderstanding you.

**Comment by cktechie2012** [comment]
Will try installing this week on spare RPi and test it.

**Comment by roenw** [comment]
Update us once you do. For now, I'll close this.
